name: Natrix
favicon: null
layout_spectrum: 0.42450688872486353
typography_spectrum: 0.07314222934655845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5210971096530557
  lightness: 0.8549594432115555
  saturation: 0.6457468753214926
  rhythmicContrast: 0.785001321695745
purpose: []
